### ISSUE TITLE
llvm 调试技巧总结

### ISSUE THREAD

**Issue by hstk30** [hstk30/hstk30.github.io#7]
1. 开启debug 信息：`-mllvm -debugs`
2. 定位引起问题的pass：opt bisect: `-mllvm -opt-bisect-limit=235`
3. `-mllvm` `-print-before=<pass-name>` `-print-after=<pass-name>` `-print-after-all` `-print-before-all`
    pass-name 在对应代码里找到，有时候是 DEBUG_TYPE，有时候是 XX_NAME
4. 定位到pass后想跳过某个pass 查看IR差异：在对应pass实现文件里查找 cl::opt ，有的好找，有的不好找， 有的在option 能找到，默认会有no 前缀，添加对应选项
5. 别名分析的一些选项: `-disable-basic-aa` `-aa-trace`
6. gdb 的时候, 遇事不决 dump() 一下
7. 比对不同版本差异，如果最新版本正确，通过`git bisect` 确定修复的commit
```
$ git bisect start
$ git bisect bad
$ git bisect good <goodcommit>
```

```
$ git bisect start
$ git bisect good
$ git bisect bad <badcommit>
```

Yes: `$ git bisect bad`
No: `$ git bisect good`

```
$ git bisect reset
```

-debug-only

-debug-pass=[Structure, Arguments]

**Comment by hstk30-hw** [comment]
lto pgo 的调试

**Comment by hstk30-hw** [comment]
-mllvm -print-before=annotation2metadata  // 打印还未进行任何优化的IR
-mllvm -print-after-all
-mllvm -debug-only=isel,legalize-types,legalizedag,dagcombine // Instruction Select 调试

**Comment by hstk30-hw** [comment]
编译llvm：

cmake -G "Ninja" -DCMAKE_BUILD_TYPE="Release" -DLLVM_ENABLE_PIC=ON -DLLVM_DEFAULT_TARGET_TRIPLE="aarch64_be-target-linux-gnu" -DLLVM_TARGETS_TO_BUILD="AArch64" -DLLVM_ENABLE_PROJECTS="clang" ../llvm

cmake -G "Ninja" -DCMAKE_BUILD_TYPE="Release" -DLLVM_ENABLE_PIC=ON -DLLVM_DEFAULT_TARGET_TRIPLE="aarch64-target-linux-gnu" -DLLVM_TARGETS_TO_BUILD="AArch64" -DLLVM_ENABLE_PROJECTS="clang" ../llvm

cmake -G "Ninja" -DCMAKE_BUILD_TYPE="Release" -DLLVM_ENABLE_PIC=ON -DLLVM_DEFAULT_TARGET_TRIPLE="armebv7a-linux-gnueabi" -DLLVM_TARGETS_TO_BUILD="ARM" -DLLVM_ENABLE_PROJECTS="clang" ../llvm
